// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "requester/Requester.hpp"

#include "OnlineSearch.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

#include <iostream>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::OnlineSearch::Interface;

class OnlineSearchHandler : virtual public OnlineSearchIf
{
public:
    OnlineSearchHandler()
    {
        // Your initialization goes here
    }

    SearchId search(const std::string& input)
    {
        std::cout << "Search=" << input << std::endl;
        
        return 0;
    }

    bool connect()
    {
        return false;
    }
};

